# Generated by Django 6.0.6 on 2026-06-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nashr', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('desc', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('color', models.CharField(choices=[('black', 'Qora'), ('white', 'Oq'), ('red', 'Qizil'), ('blue', 'Kok'), ('gray', 'Kulrang')], max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kitob/')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'kitoblar ',
                'ordering': ['-id'],
            },
        ),
    ]
