# Generated by Django 5.1.11 on 2026-06-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitoblar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
